### ISSUE TITLE
About resolution

### ISSUE THREAD

**Issue by allen-li-webpower** [admetricks/printer-webservice#4]
I have a problem about the resolution .It seems that 1024x768x24 is invalid.
http://stackoverflow.com/questions/22913794/setting-a-resolution-for-xvfb-run-and-wkhtmltopdf-wkhtmltoimage
So the code should be "xvfb-run --server-args="-screen 0, 1024x768x24" /usr/local/bin/wkhtmltopdf **--use-xserver** $*" in the file wkhtmltopdf.sh

**Comment by allen-li-webpower** [comment]
After I pull the docker image in hub.docker.com, I want to change the file 'wkhtmltopdf.sh',but the user is not root(printer_service),and I don't know the password.
So I suggest you can use root or tell the password in Dockerfile.

**Comment by pdelsol** [comment]
@allen-li-webpower thanks for your feedback
- we are fixing the resolution issue in the next pull request
- you can change the file with `docker cp` it is safer to have a non-root user
